# Generated by Django 4.2.4 on 2023-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='chat_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
