# Generated by Django 4.2.4 on 2023-11-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='chat_id',
        ),
    ]
